import os
import pytest
import torch
from src.model_config import LABELS, THRESHOLD

WEIGHTED_F1_THRESHOLD = 0.70

TEST_PHRASES = [
    # alegria
    ("Estou muito feliz hoje", "alegria"),
    ("Que dia maravilhoso", "alegria"),
    ("Consegui passar no exame", "alegria"),
    ("Adorei a surpresa que você me fez", "alegria"),
    ("Estou radiante com a notícia", "alegria"),
    ("Que alegria ver todo mundo reunido", "alegria"),
    ("Estou pulando de felicidade", "alegria"),
    ("Hoje é um dia de sol e alegria", "alegria"),
    ("Meu time ganhou o campeonato", "alegria"),
    ("Recebi uma promoção no trabalho", "alegria"),
    ("Que bom te ver depois de tanto tempo", "alegria"),
    ("Estou animado com a viagem", "alegria"),
    ("Consegui resolver aquele problema", "alegria"),
    ("Minha família está toda bem", "alegria"),
    ("Nada como um bom café da manhã", "alegria"),
    ("Adoro quando as coisas dão certo", "alegria"),
    ("Estou realizado com meu trabalho", "alegria"),
    ("Que delícia esse momento", "alegria"),
    ("Me sinto leve e feliz", "alegria"),
    ("Estou vibrando com a conquista", "alegria"),
    ("Hoje acordei com o pé direito", "alegria"),
    ("Consegui completar todos os meus objetivos", "alegria"),
    ("Estou muito contente com o resultado", "alegria"),
    ("Que bom encontrar um amigo", "alegria"),
    ("Adoro dias ensolarados como hoje", "alegria"),
    ("Meu coração está cheio de alegria", "alegria"),
    ("Que dia perfeito para um passeio", "alegria"),
    ("Estou aproveitando cada momento", "alegria"),
    ("Hoje tudo deu certo", "alegria"),
    ("Meu projeto foi aprovado", "alegria"),
    ("Estou muito orgulhoso de mim", "alegria"),
    ("Que sensação boa estar aqui", "alegria"),
    ("Estou sorrindo sem parar", "alegria"),
    ("As coisas estão fluindo bem", "alegria"),
    ("Estou me sentindo realizado", "alegria"),
    ("Hoje é um ótimo dia para celebrar", "alegria"),
    ("Consegui superar aquele desafio", "alegria"),
    ("Estou muito grato e feliz com a vida", "alegria"),
    ("Me sinto abençoado", "alegria"),
    ("Que dia iluminado", "alegria"),
    ("Estou eufórico com a novidade", "alegria"),
    ("Me sinto nas nuvens", "alegria"),
    ("Estou empolgado com o que vem por aí", "alegria"),
    ("Que alegria receber essa notícia", "alegria"),
    ("A vida está boa demais", "alegria"),
    ("Estou tão feliz que poderia pular", "alegria"),
    ("Adoro quando me surpreendem positivamente", "alegria"),
    ("Estou me sentindo ótimo hoje", "alegria"),

    # tristeza
    ("Estou muito triste hoje", "tristeza"),
    ("Que notícia triste", "tristeza"),
    ("Estou me sentindo sozinho", "tristeza"),
    ("Meu coração está partido", "tristeza"),
    ("Chorei a noite toda", "tristeza"),
    ("Perdi alguém importante", "tristeza"),
    ("Estou desanimado com a vida", "tristeza"),
    ("Tudo parece sem graça", "tristeza"),
    ("Não tenho vontade de fazer nada", "tristeza"),
    ("Estou passando por um momento difícil", "tristeza"),
    ("Sinto uma dor no peito", "tristeza"),
    ("Hoje estou mais pra baixo", "tristeza"),
    ("Estou com o coração apertado", "tristeza"),
    ("Me despedi de alguém querido", "tristeza"),
    ("Estou sentindo uma tristeza profunda", "tristeza"),
    ("O dia está cinza e nublado", "tristeza"),
    ("Nada me anima hoje", "tristeza"),
    ("Sinto que decepcionei todo mundo", "tristeza"),
    ("Estou de luto", "tristeza"),
    ("Faz tempo que não me sinto bem", "tristeza"),
    ("Estou com o coração pesado", "tristeza"),
    ("Não consigo parar de pensar no que aconteceu", "tristeza"),
    ("Estou me sentindo um fracasso", "tristeza"),
    ("Perdi meu emprego e estou arrasado", "tristeza"),
    ("Minha semana foi horrível", "tristeza"),
    ("Não vejo saída para essa situação", "tristeza"),
    ("Estou cansado de sofrer", "tristeza"),
    ("Meu relacionamento terminou", "tristeza"),
    ("Tudo me faz chorar hoje", "tristeza"),
    ("A vida parece injusta", "tristeza"),
    ("Estou num dia de luto e reflexão", "tristeza"),
    ("Estou desolado com a notícia", "tristeza"),
    ("Sinto um vazio dentro de mim", "tristeza"),
    ("Não consigo me concentrar em nada", "tristeza"),
    ("Minha energia está no chão", "tristeza"),
    ("O término do meu namoro me destruiu", "tristeza"),
    ("Estou num dia melancólico", "tristeza"),
    ("Só queria ficar na cama", "tristeza"),
    ("Nada me traz alegria ultimamente", "tristeza"),
    ("Estou afogado em lágrimas", "tristeza"),
    ("Perder meu cachorro foi devastador", "tristeza"),
    ("A semana começou mal", "tristeza"),
    ("Não estou bem hoje não", "tristeza"),
    ("Sinto uma tristeza que não passa", "tristeza"),
    ("A solidão está me consumindo", "tristeza"),
    ("Estou sentindo falta da minha avó", "tristeza"),

    # raiva
    ("Estou com muita raiva", "raiva"),
    ("Isso me irrita profundamente", "raiva"),
    ("Que absurdo o que fizeram", "raiva"),
    ("Estou furioso com isso", "raiva"),
    ("Isso é uma falta de respeito", "raiva"),
    ("Estou pistola com essa situação", "raiva"),
    ("Isso não se faz", "raiva"),
    ("Estou indignado com essa injustiça", "raiva"),
    ("O trânsito hoje me tirou do sério", "raiva"),
    ("Não suporto gente desonesta", "raiva"),
    ("Estou fervendo de raiva", "raiva"),
    ("Isso ultrapassou todos os limites", "raiva"),
    ("Meu chefe foi injusto comigo", "raiva"),
    ("Não aguento mais essa situação", "raiva"),
    ("Que ódio dessa pessoa", "raiva"),
    ("Isso me deixou muito bravo", "raiva"),
    ("Que raiva de quem não cumpre o que promete", "raiva"),
    ("Estou puto com a situação", "raiva"),
    ("Isso é um absurdo completo", "raiva"),
    ("Minha paciência acabou", "raiva"),
    ("Me tiraram do sério", "raiva"),
    ("Isso me deixa possesso", "raiva"),
    ("Estou cheio de gente folgada", "raiva"),
    ("Que raiva desse trânsito", "raiva"),
    ("Isso foi a gota d'água", "raiva"),
    ("Não vou aceitar esse desaforo", "raiva"),
    ("Estou muito irritado com você", "raiva"),
    ("Isso me fez ferver o sangue", "raiva"),
    ("Fui tratado com desrespeito", "raiva"),
    ("Isso é inaceitável", "raiva"),
    ("Estou com ódio dessa situação", "raiva"),
    ("Me enganaram e estou furioso", "raiva"),
    ("Não suporto injustiça", "raiva"),
    ("Estou borbulhando de raiva", "raiva"),
    ("Isso é um desrespeito total", "raiva"),
    ("Não posso acreditar nessa palhaçada", "raiva"),
    ("Estou revoltado com a política", "raiva"),
    ("Isso é um descaso total", "raiva"),
    ("Perdi a paciência de vez", "raiva"),
    ("Isso me tira do sério profundamente", "raiva"),
    ("Não admito esse tipo de atitude", "raiva"),
    ("Que raiva dessa burocracia toda", "raiva"),
    ("Você me fez perder a cabeça", "raiva"),
    ("Fizeram isso de propósito", "raiva"),
    ("Que falta de consideração", "raiva"),
    ("Isso é inacreditável", "raiva"),

    # medo
    ("Estou com muito medo", "medo"),
    ("Sinto um medo inexplicável", "medo"),
    ("Estou apavorado com o resultado", "medo"),
    ("Tenho pavor de escuro", "medo"),
    ("Sinto frio na espinha", "medo"),
    ("Estou com um pressentimento ruim", "medo"),
    ("Meu coração está na mão", "medo"),
    ("Estou com medo do resultado dos exames", "medo"),
    ("Estou morrendo de medo da cirurgia", "medo"),
    ("Fiquei paralisado de medo", "medo"),
    ("Tenho medo de altura", "medo"),
    ("Estou tremendo de medo", "medo"),
    ("Ouvi um barulho estranho", "medo"),
    ("Estou com medo de dirigir na chuva", "medo"),
    ("Me deu um susto danado", "medo"),
    ("Tenho medo de perder meu emprego", "medo"),
    ("Estou com medo de avião", "medo"),
    ("Me assustei com o que vi", "medo"),
    ("Estou temeroso com a entrevista", "medo"),
    ("Aquela situação me amedrontou", "medo"),
    ("Sinto medo de falar em público", "medo"),
    ("Estou com receio do que vem pela frente", "medo"),
    ("Tenho pavor de barata", "medo"),
    ("Me sinto ameaçado", "medo"),
    ("Estou apavorado de verdade", "medo"),
    ("Estou com medo de andar de noite", "medo"),
    ("O escuro me assusta", "medo"),
    ("Sinto um calafrio toda vez que penso nisso", "medo"),
    ("Estou em pânico com essa situação", "medo"),
    ("Tenho medo de aranhas", "medo"),
    ("O médico falou uma coisa que me assustou", "medo"),
    ("Me sinto inseguro nesse lugar", "medo"),
    ("Não sei o que fazer e isso me apavora", "medo"),
    ("Fiquei petrificado quando vi", "medo"),
    ("Tenho medo de injeção", "medo"),
    ("Só de pensar já me arrepio", "medo"),
    ("Estou morrendo de medo de errar", "medo"),
    ("A violência na cidade me apavora", "medo"),
    ("Tremo só de pensar no que pode acontecer", "medo"),
    ("Preciso de ajuda estou com muito medo", "medo"),
    ("Estou com medo de não conseguir", "medo"),
    ("Aquela sombra me assustou", "medo"),
    ("O barulho noturno me apavora", "medo"),
    ("Estou em pânico sem saber o que fazer", "medo"),
    ("Fiquei acordado de medo a noite toda", "medo"),

    # nojo
    ("Que nojo dessa comida", "nojo"),
    ("Estou enjoado só de olhar", "nojo"),
    ("Isso é repugnante", "nojo"),
    ("Que nojo desse lugar sujo", "nojo"),
    ("Isso me causa repulsa", "nojo"),
    ("Isso é nojento", "nojo"),
    ("Estou com ânsia só de pensar", "nojo"),
    ("Não consigo tocar nisso de nojo", "nojo"),
    ("Isso me dá ânsia de vômito", "nojo"),
    ("Que nojo do banheiro público", "nojo"),
    ("Estou com asco dessa situação", "nojo"),
    ("Isso é asqueroso", "nojo"),
    ("Que nojo de gente mal educada", "nojo"),
    ("O cheiro está horrível", "nojo"),
    ("Que nojo desse bicho", "nojo"),
    ("A comida estava estragada", "nojo"),
    ("Isso me enjoa profundamente", "nojo"),
    ("Não suporto o cheiro de ovo", "nojo"),
    ("Só de ver já sinto repulsa", "nojo"),
    ("Que nojo de sangue", "nojo"),
    ("Isso é grotesco", "nojo"),
    ("O lixo está fedendo", "nojo"),
    ("Estou com nojo desse lugar", "nojo"),
    ("Isso é nojento demais", "nojo"),
    ("Senti um embrulho no estômago", "nojo"),
    ("Que nojo de inseto", "nojo"),
    ("Isso me causa nojo profundo", "nojo"),
    ("Comida estragada é nojenta", "nojo"),
    ("O vaso sanitário estava imundo", "nojo"),
    ("Isso me revira o estômago", "nojo"),
    ("A textura dessa comida é nojenta", "nojo"),
    ("Senti asco quando vi", "nojo"),
    ("O cheiro de peixe podre é horrível", "nojo"),
    ("Aquela coisa viscosa me deu nojo", "nojo"),
    ("O banheiro está nojento", "nojo"),
    ("Não suporto ver sangue coagulado", "nojo"),
    ("Isso me dá repulsa moral", "nojo"),
    ("Que nojo de gente que não lava a mão", "nojo"),
    ("A cozinha estava infestada de baratas", "nojo"),
    ("Isso é repulsivo", "nojo"),
    ("O lixo está transbordando", "nojo"),
    ("Aquilo me causou nojo extremo", "nojo"),
    ("Isso me causa repulsa física", "nojo"),

    # surpresa
    ("Nossa que surpresa", "surpresa"),
    ("Não esperava por isso", "surpresa"),
    ("Que surpresa maravilhosa", "surpresa"),
    ("Fiquei chocado com a notícia", "surpresa"),
    ("Isso me surpreendeu totalmente", "surpresa"),
    ("Nem acredito que isso aconteceu", "surpresa"),
    ("Que surpresa boa te encontrar aqui", "surpresa"),
    ("Fiquei boquiaberto", "surpresa"),
    ("Isso foi inesperado", "surpresa"),
    ("Fiquei perplexo com a situação", "surpresa"),
    ("Que surpresa desagradável", "surpresa"),
    ("Nunca imaginei que fosse assim", "surpresa"),
    ("Fui pego de surpresa", "surpresa"),
    ("Isso mudou tudo que eu esperava", "surpresa"),
    ("Fiquei pasmo com o resultado", "surpresa"),
    ("Isso é uma grande surpresa", "surpresa"),
    ("Fiquei espantado com o que vi", "surpresa"),
    ("Não esperava essa reviravolta", "surpresa"),
    ("Que reviravolta incrível", "surpresa"),
    ("A notícia me deixou estupefato", "surpresa"),
    ("Foi uma surpresa completa", "surpresa"),
    ("Não estava nos meus planos", "surpresa"),
    ("Me pegou desprevenido", "surpresa"),
    ("Isso veio do nada", "surpresa"),
    ("Uau que surpresa incrível", "surpresa"),
    ("Foi totalmente inesperado", "surpresa"),
    ("Estou surpreso com a rapidez", "surpresa"),
    ("Que plot twist inesperado", "surpresa"),
    ("A vida me surpreendeu hoje", "surpresa"),
    ("Fiquei sem reação", "surpresa"),
    ("Isso não estava no roteiro", "surpresa"),
    ("A notícia me deixou sem palavras", "surpresa"),
    ("Não acredito que você veio", "surpresa"),
    ("Isso é tão inesperado", "surpresa"),
    ("Nunca pensei que veria isso", "surpresa"),
    ("Minha reação foi de choque", "surpresa"),
    ("Foi uma surpresa agradável", "surpresa"),
    ("Que surpresa encontrar isso", "surpresa"),
    ("Minha cara de surpresa", "surpresa"),
    ("Cai a ficha", "surpresa"),
    ("Só agora entendi o que aconteceu", "surpresa"),
    ("Pensei que era uma coisa era outra", "surpresa"),
    ("Foi uma baita surpresa", "surpresa"),
    ("Surpresa total", "surpresa"),

    # ansiedade
    ("Estou muito ansioso", "ansiedade"),
    ("Não consigo parar de pensar", "ansiedade"),
    ("Estou com a ansiedade a mil", "ansiedade"),
    ("Meu coração está acelerado", "ansiedade"),
    ("Preciso de respostas logo", "ansiedade"),
    ("Estou preocupado com a prova", "ansiedade"),
    ("Não consigo ficar parado", "ansiedade"),
    ("Estou com um nó na garganta", "ansiedade"),
    ("Sinto uma inquietação no corpo", "ansiedade"),
    ("Não consigo dormir pensando nisso", "ansiedade"),
    ("Estou contando os minutos", "ansiedade"),
    ("Minha mente não desliga", "ansiedade"),
    ("Estou muito tenso", "ansiedade"),
    ("Sinto borboletas no estômago", "ansiedade"),
    ("Estou agoniado esperando o resultado", "ansiedade"),
    ("O nervosismo está me consumindo", "ansiedade"),
    ("Estou com crise de ansiedade", "ansiedade"),
    ("Não consigo respirar fundo", "ansiedade"),
    ("Estou em estado de alerta", "ansiedade"),
    ("Mergulhei em pensamentos ruins", "ansiedade"),
    ("Estou com a respiração ofegante", "ansiedade"),
    ("Não consigo me concentrar", "ansiedade"),
    ("Estou com taquicardia", "ansiedade"),
    ("Preciso me acalmar", "ansiedade"),
    ("A preocupação está tomando conta", "ansiedade"),
    ("O peito está apertado", "ansiedade"),
    ("Fico pensando no pior cenário", "ansiedade"),
    ("Não vejo a hora disso acabar", "ansiedade"),
    ("Estou ansioso pela consulta", "ansiedade"),
    ("Meu pensamento não para", "ansiedade"),
    ("Estou roendo as unhas sem perceber", "ansiedade"),
    ("O frio na barriga não passa", "ansiedade"),
    ("Estou em pânico com o prazo", "ansiedade"),
    ("Sinto uma pressão no peito", "ansiedade"),
    ("Estou agoniado sem motivo", "ansiedade"),
    ("Não consigo parar de mexer as pernas", "ansiedade"),
    ("Estou com insônia de ansiedade", "ansiedade"),
    ("Aguardo ansiosamente pela resposta", "ansiedade"),
    ("Estou com um frio na barriga danado", "ansiedade"),
    ("Me sinto inquieto", "ansiedade"),
    ("A ansiedade está me matando", "ansiedade"),
    ("Estou com taquicardia de nervoso", "ansiedade"),
    ("Não consigo parar de pensar no amanhã", "ansiedade"),
    ("Estou muito preocupado", "ansiedade"),
    ("A espera está me deixando louco", "ansiedade"),

    # vergonha
    ("Estou com muita vergonha", "vergonha"),
    ("Que situação constrangedora", "vergonha"),
    ("Falei besteira na reunião", "vergonha"),
    ("Meu rosto está vermelho de vergonha", "vergonha"),
    ("Todo mundo me olhou", "vergonha"),
    ("Fiz papel de bobo", "vergonha"),
    ("Caí no meio da rua", "vergonha"),
    ("Não sei onde enfiar a cara", "vergonha"),
    ("Me chamaram atenção na frente de todos", "vergonha"),
    ("Que vergonha do que eu fiz", "vergonha"),
    ("Errei o nome da pessoa", "vergonha"),
    ("Fiquei sem jeito", "vergonha"),
    ("Que mico o que eu passei", "vergonha"),
    ("Eu queria sumir na hora", "vergonha"),
    ("Todo mundo riu de mim", "vergonha"),
    ("Foi muito constrangedor", "vergonha"),
    ("Senti vergonha alheia", "vergonha"),
    ("Gaguejei na apresentação", "vergonha"),
    ("Derramei café na camisa", "vergonha"),
    ("Me pegaram no flagra", "vergonha"),
    ("Que vergonha de ter feito isso", "vergonha"),
    ("Fiquei encabulado", "vergonha"),
    ("Todo mundo viu meu erro", "vergonha"),
    ("O microfone estava ligado", "vergonha"),
    ("Falei algo que não devia", "vergonha"),
    ("Me arrependi na hora que falei", "vergonha"),
    ("Que vergonha de cantar desafinado", "vergonha"),
    ("Tropecei na frente de todo mundo", "vergonha"),
    ("Esqueci o texto na hora de falar", "vergonha"),
    ("Foi uma situação humilhante", "vergonha"),
    ("Estou com vergonha de olhar nos olhos", "vergonha"),
    ("Fiquei envergonhado com o elogio", "vergonha"),
    ("Me senti exposto", "vergonha"),
    ("Não queria ter feito aquilo", "vergonha"),
    ("Que vergonha de errar o nome", "vergonha"),
    ("Meu segredo foi revelado", "vergonha"),
    ("Todo mundo ficou me olhando", "vergonha"),
    ("Foi a maior vergonha da minha vida", "vergonha"),
    ("Não consigo esquecer essa situação", "vergonha"),
    ("Estou morrendo de vergonha", "vergonha"),
    ("Passei vergonha na frente dela", "vergonha"),
    ("Falei algo inconveniente", "vergonha"),
    ("Senti meu rosto queimar", "vergonha"),

    # culpa
    ("Me sinto culpado", "culpa"),
    ("Foi minha culpa", "culpa"),
    ("Eu deveria ter feito diferente", "culpa"),
    ("Me arrependo do que fiz", "culpa"),
    ("Magoei alguém que amo", "culpa"),
    ("Não consigo me perdoar", "culpa"),
    ("Fui injusto com ele", "culpa"),
    ("Poderia ter evitado isso", "culpa"),
    ("O peso da culpa está me matando", "culpa"),
    ("Não devia ter falado aquilo", "culpa"),
    ("Fui irresponsável", "culpa"),
    ("Decepcionei minha família", "culpa"),
    ("Sinto remorso pelo que fiz", "culpa"),
    ("Estou com peso na consciência", "culpa"),
    ("A culpa não me deixa dormir", "culpa"),
    ("Se eu pudesse voltar atrás", "culpa"),
    ("Fui egoísta", "culpa"),
    ("Eu errei feio dessa vez", "culpa"),
    ("Esqueci do compromisso importante", "culpa"),
    ("Fui grosso sem necessidade", "culpa"),
    ("Não fiz o que prometi", "culpa"),
    ("Deixei eles na mão", "culpa"),
    ("Menti e agora me arrependo", "culpa"),
    ("Sinto que estraguei tudo", "culpa"),
    ("Fiz algo imperdoável", "culpa"),
    ("O remorso está me consumindo", "culpa"),
    ("Fui omisso quando deveria agir", "culpa"),
    ("Não posso consertar o que fiz", "culpa"),
    ("A culpa está me corroendo", "culpa"),
    ("Devia ter estado lá", "culpa"),
    ("Não fui um bom amigo", "culpa"),
    ("Decepcionei a mim mesmo", "culpa"),
    ("Fui negligente", "culpa"),
    ("Eu causei isso", "culpa"),
    ("Preciso de perdão", "culpa"),
    ("Fui ingrato", "culpa"),
    ("Me arrependo amargamente", "culpa"),
    ("Devia ter pedido desculpas", "culpa"),
    ("Fui covarde", "culpa"),
    ("O sentimento de culpa é forte", "culpa"),
    ("Falei demais e me arrependi", "culpa"),
    ("A consciência está pesada", "culpa"),

    # saudade
    ("Estou com saudade da minha avó", "saudade"),
    ("Que saudade daquela época", "saudade"),
    ("Sinto falta dos velhos tempos", "saudade"),
    ("Sinto falta de você", "saudade"),
    ("Que saudade do meu pai", "saudade"),
    ("Sinto falta da nossa amizade", "saudade"),
    ("Que saudade de casa", "saudade"),
    ("Lembro com carinho da infância", "saudade"),
    ("Que saudade daquele lugar", "saudade"),
    ("Sinto falta do abraço dela", "saudade"),
    ("Sinto saudade de quem eu era", "saudade"),
    ("Que saudade das férias", "saudade"),
    ("Sinto falta do cheiro da casa dela", "saudade"),
    ("Saudade aperta o coração", "saudade"),
    ("Que falta ele me faz", "saudade"),
    ("Sinto falta da nossa conversa", "saudade"),
    ("Que saudade da comida da minha mãe", "saudade"),
    ("Sinto falta da praia", "saudade"),
    ("Que saudade do meu gato", "saudade"),
    ("Sinto falta dos abraços apertados", "saudade"),
    ("Lembranças que aquecem o coração", "saudade"),
    ("Sinto falta da inocência", "saudade"),
    ("Nostalgia tomou conta de mim", "saudade"),
    ("Que saudade do tempo de escola", "saudade"),
    ("Sinto falta do calor humano", "saudade"),
    ("A saudade dói demais", "saudade"),
    ("Que falta faz um amigo", "saudade"),
    ("Sinto falta daquele sorriso", "saudade"),
    ("Que saudade de quando éramos felizes", "saudade"),
    ("Sinto falta de ser criança", "saudade"),
    ("A distância machuca", "saudade"),
    ("Sinto falta do jeito dela", "saudade"),
    ("Que saudade da nossa música", "saudade"),
    ("Sinto falta de quem partiu", "saudade"),
    ("Que saudade daquele olhar", "saudade"),
    ("O peito aperta de saudade", "saudade"),
    ("Sinto falta de quem eu amava", "saudade"),
    ("Que saudade dos momentos simples", "saudade"),
    ("Sinto falta do abraço", "saudade"),
    ("Sinto falta do riso dele", "saudade"),
    ("A lembrança me faz bem", "saudade"),
    ("Sinto falta da cidade onde cresci", "saudade"),
    ("Que saudade de brincar na rua", "saudade"),
    ("Sinto falta do meu antigo eu", "saudade"),
    ("Sinto falta do aconchego do lar", "saudade"),

    # amor
    ("Eu te amo", "amor"),
    ("Estou apaixonado", "amor"),
    ("Você é o amor da minha vida", "amor"),
    ("Meu coração é seu", "amor"),
    ("Sinto um amor imenso por você", "amor"),
    ("Que bom te ter na minha vida", "amor"),
    ("Você me completa", "amor"),
    ("Adoro passar tempo com você", "amor"),
    ("Amo minha família", "amor"),
    ("Você é especial para mim", "amor"),
    ("Te amo mais que tudo", "amor"),
    ("O amor que sinto é puro", "amor"),
    ("Meu coração transborda de amor", "amor"),
    ("Nada supera o amor de mãe", "amor"),
    ("Que amor pelos meus amigos", "amor"),
    ("Adoro cuidar de quem amo", "amor"),
    ("Amo estar com você", "amor"),
    ("Te amo incondicionalmente", "amor"),
    ("Você é importante pra mim", "amor"),
    ("Amo passar os dias ao seu lado", "amor"),
    ("Que amor de pessoa você é", "amor"),
    ("Sinto muito afeto por você", "amor"),
    ("Amo cada momento juntos", "amor"),
    ("Você aquece meu coração", "amor"),
    ("Meu amor por você é infinito", "amor"),
    ("Sinto um carinho imenso", "amor"),
    ("Amo como você é", "amor"),
    ("Você é minha pessoa favorita", "amor"),
    ("Te amo desde o primeiro dia", "amor"),
    ("O amor é o que nos une", "amor"),
    ("Me sinto amado", "amor"),
    ("Amor é o que sinto agora", "amor"),
    ("Que amor genuíno", "amor"),
    ("Você me faz tão bem", "amor"),
    ("Te adoro demais", "amor"),
    ("Você ilumina meus dias", "amor"),
    ("Que amor de filho que eu tenho", "amor"),
    ("Te amo mais a cada dia", "amor"),
    ("Você é minha casa", "amor"),
    ("Sinto um amor profundo", "amor"),
    ("Amor verdadeiro não se explica", "amor"),
    ("Que amor que sinto agora", "amor"),
    ("O amor está no ar", "amor"),
    ("Te amo e é recíproco", "amor"),
    ("Você é tudo para mim", "amor"),

    # gratidão
    ("Sou muito grato por tudo", "gratidão"),
    ("Obrigado por tudo", "gratidão"),
    ("Agradeço muito pela ajuda", "gratidão"),
    ("Estou muito grato pela vida", "gratidão"),
    ("Sou grato pela família que tenho", "gratidão"),
    ("Obrigado por existir", "gratidão"),
    ("Agradeço todos os dias", "gratidão"),
    ("Gratidão pela oportunidade", "gratidão"),
    ("Sou grato pelo meu trabalho", "gratidão"),
    ("Agradeço pela sua amizade", "gratidão"),
    ("Que gratidão imensa", "gratidão"),
    ("Obrigado pelo apoio", "gratidão"),
    ("Sou grato pela minha saúde", "gratidão"),
    ("Meu coração é grato", "gratidão"),
    ("Gratidão por mais um dia", "gratidão"),
    ("Sou grato por ter onde morar", "gratidão"),
    ("Agradeço pela compreensão", "gratidão"),
    ("Sou grato pela sua paciência", "gratidão"),
    ("Que grato sou pelos amigos", "gratidão"),
    ("Agradeço pela sua generosidade", "gratidão"),
    ("Sou grato pelas pequenas coisas", "gratidão"),
    ("Hoje só tenho a agradecer", "gratidão"),
    ("Gratidão é o sentimento de hoje", "gratidão"),
    ("Sou grato por acordar hoje", "gratidão"),
    ("Agradeço pela sua presença", "gratidão"),
    ("Sou grato por aprender com os erros", "gratidão"),
    ("Que grato estou hoje", "gratidão"),
    ("Obrigado pelo carinho de sempre", "gratidão"),
    ("Agradeço por cada oportunidade", "gratidão"),
    ("Sou grato pela natureza", "gratidão"),
    ("Me sinto abençoado e grato", "gratidão"),
    ("Obrigado por me ensinar tanto", "gratidão"),
    ("Gratidão profunda", "gratidão"),
    ("Sou grato por cada amanhecer", "gratidão"),
    ("Agradeço pela confiança", "gratidão"),
    ("Obrigado por existir em minha vida", "gratidão"),
    ("Sou grato pelo presente que é a vida", "gratidão"),
    ("Agradeço pelo seu tempo", "gratidão"),
    ("Gratidão por tudo que vivi", "gratidão"),
    ("Sou grato por ter você", "gratidão"),
    ("Obrigado por cada lição", "gratidão"),
    ("Agradeço de coração", "gratidão"),
    ("Me sinto grato por tudo", "gratidão"),
    ("Muito obrigado mesmo", "gratidão"),
    ("Sou grato pela sua amizade sincera", "gratidão"),

    # neutro
    ("Hoje está um dia nublado", "neutro"),
    ("Vou ao mercado mais tarde", "neutro"),
    ("O café está pronto", "neutro"),
    ("São três horas da tarde", "neutro"),
    ("Preciso comprar arroz", "neutro"),
    ("A reunião é amanhã", "neutro"),
    ("Vou ler um livro hoje", "neutro"),
    ("Terminei de almoçar", "neutro"),
    ("Vou caminhar um pouco", "neutro"),
    ("O telefone tocou", "neutro"),
    ("Estou indo para o trabalho", "neutro"),
    ("A porta está aberta", "neutro"),
    ("Tem um passarinho no jardim", "neutro"),
    ("Vou pagar as contas hoje", "neutro"),
    ("O final de semana chegou", "neutro"),
    ("A casa está arrumada", "neutro"),
    ("Vou visitar minha mãe", "neutro"),
    ("O carro precisa de revisão", "neutro"),
    ("A janela está quebrada", "neutro"),
    ("Tem fila no banco", "neutro"),
    ("O gato está dormindo", "neutro"),
    ("A televisão está ligada", "neutro"),
    ("Vou pegar um ônibus", "neutro"),
    ("A loja abre às oito", "neutro"),
    ("Preciso lavar a roupa", "neutro"),
    ("O jantar está na mesa", "neutro"),
    ("Vou regar as plantas", "neutro"),
    ("A água está quente", "neutro"),
    ("O computador está lento", "neutro"),
    ("O banco está fechado", "neutro"),
    ("Vou ao dentista na terça", "neutro"),
    ("O celular descarregou", "neutro"),
    ("A chuva parou", "neutro"),
    ("Vou trocar de roupa", "neutro"),
    ("O correio entregou a encomenda", "neutro"),
    ("A farmácia está aberta", "neutro"),
    ("Vou preparar o almoço", "neutro"),
    ("O cachorro latiu", "neutro"),
    ("Passei no mercado", "neutro"),
    ("O ônibus chegou atrasado", "neutro"),
    ("Vou pagar o aluguel", "neutro"),
    ("A pizza está sendo entregue", "neutro"),
    ("Vou pendurar o quadro", "neutro"),
    ("Vou ver o que está passando na televisão", "neutro"),
    ("O sofá é confortável", "neutro"),
]


def test_phrases_count():
    from collections import Counter
    labels = [p[1] for p in TEST_PHRASES]
    counts = Counter(labels)
    for label in LABELS:
        assert counts[label] >= 40, f"{label} only has {counts[label]} phrases"
    assert len(TEST_PHRASES) >= 13 * 40


def test_phrases_labels_valid():
    for _, expected_label in TEST_PHRASES:
        assert expected_label in LABELS, f"Invalid label: {expected_label}"


@pytest.mark.skipif(
    not os.path.exists(os.environ.get("MODEL_PATH", "/model")),
    reason="No trained model artifact at MODEL_PATH — run training first"
)
def test_weighted_f1_threshold():
    import evaluate
    from src.classifier import EmotionClassifier
    from src.model_config import MODEL_PATH

    model_path = os.environ.get("MODEL_PATH", MODEL_PATH)
    classifier = EmotionClassifier(model_path)

    y_true = []
    y_pred = []

    for text, expected_label in TEST_PHRASES:
        result = classifier.predict(text)
        true_vec = [1 if label == expected_label else 0 for label in LABELS]
        pred_vec = [
            1 if score >= THRESHOLD else 0
            for label, score in result["scores"].items()
        ]
        if sum(pred_vec) == 0:
            pred_vec[LABELS.index(result["emotion_principal"])] = 1
        y_true.append(true_vec)
        y_pred.append(pred_vec)

    f1_metric = evaluate.load("f1", config_name="multilabel")
    result = f1_metric.compute(
        predictions=y_pred, references=y_true, average="weighted"
    )
    weighted_f1 = result["f1"]

    print(f"\nWeighted F1: {weighted_f1:.4f} (threshold: {WEIGHTED_F1_THRESHOLD})")
    assert weighted_f1 >= WEIGHTED_F1_THRESHOLD, (
        f"Weighted F1 {weighted_f1:.4f} < {WEIGHTED_F1_THRESHOLD} — "
        f"run D-29 iteration (more data + hyperparameter tuning)"
    )
