// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: analysis.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegistroId    string                 `protobuf:"bytes,1,opt,name=registro_id,json=registroId,proto3" json:"registro_id,omitempty"`
	Sensacoes     string                 `protobuf:"bytes,2,opt,name=sensacoes,proto3" json:"sensacoes,omitempty"`
	Contexto      string                 `protobuf:"bytes,3,opt,name=contexto,proto3" json:"contexto,omitempty"`
	Pensamentos   string                 `protobuf:"bytes,4,opt,name=pensamentos,proto3" json:"pensamentos,omitempty"`
	DataHora      string                 `protobuf:"bytes,5,opt,name=data_hora,json=dataHora,proto3" json:"data_hora,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetRegistroId() string {
	if x != nil {
		return x.RegistroId
	}
	return ""
}

func (x *AnalyzeRequest) GetSensacoes() string {
	if x != nil {
		return x.Sensacoes
	}
	return ""
}

func (x *AnalyzeRequest) GetContexto() string {
	if x != nil {
		return x.Contexto
	}
	return ""
}

func (x *AnalyzeRequest) GetPensamentos() string {
	if x != nil {
		return x.Pensamentos
	}
	return ""
}

func (x *AnalyzeRequest) GetDataHora() string {
	if x != nil {
		return x.DataHora
	}
	return ""
}

type EmotionScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emotion       string                 `protobuf:"bytes,1,opt,name=emotion,proto3" json:"emotion,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmotionScore) Reset() {
	*x = EmotionScore{}
	mi := &file_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionScore) ProtoMessage() {}

func (x *EmotionScore) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionScore.ProtoReflect.Descriptor instead.
func (*EmotionScore) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *EmotionScore) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *EmotionScore) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type AnalyzeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EmotionPrincipal string                 `protobuf:"bytes,1,opt,name=emotion_principal,json=emotionPrincipal,proto3" json:"emotion_principal,omitempty"`
	Emotions         []*EmotionScore        `protobuf:"bytes,2,rep,name=emotions,proto3" json:"emotions,omitempty"`
	Scores           map[string]float32     `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	Intensidade      float32                `protobuf:"fixed32,4,opt,name=intensidade,proto3" json:"intensidade,omitempty"`
	AnaliseAdicional string                 `protobuf:"bytes,5,opt,name=analise_adicional,json=analiseAdicional,proto3" json:"analise_adicional,omitempty"`
	ModeloVersao     string                 `protobuf:"bytes,6,opt,name=modelo_versao,json=modeloVersao,proto3" json:"modelo_versao,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeResponse) GetEmotionPrincipal() string {
	if x != nil {
		return x.EmotionPrincipal
	}
	return ""
}

func (x *AnalyzeResponse) GetEmotions() []*EmotionScore {
	if x != nil {
		return x.Emotions
	}
	return nil
}

func (x *AnalyzeResponse) GetScores() map[string]float32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *AnalyzeResponse) GetIntensidade() float32 {
	if x != nil {
		return x.Intensidade
	}
	return 0
}

func (x *AnalyzeResponse) GetAnaliseAdicional() string {
	if x != nil {
		return x.AnaliseAdicional
	}
	return ""
}

func (x *AnalyzeResponse) GetModeloVersao() string {
	if x != nil {
		return x.ModeloVersao
	}
	return ""
}

var File_analysis_proto protoreflect.FileDescriptor

const file_analysis_proto_rawDesc = "" +
	"\n" +
	"\x0eanalysis.proto\x12\x03nlp\"\xaa\x01\n" +
	"\x0eAnalyzeRequest\x12\x1f\n" +
	"\vregistro_id\x18\x01 \x01(\tR\n" +
	"registroId\x12\x1c\n" +
	"\tsensacoes\x18\x02 \x01(\tR\tsensacoes\x12\x1a\n" +
	"\bcontexto\x18\x03 \x01(\tR\bcontexto\x12 \n" +
	"\vpensamentos\x18\x04 \x01(\tR\vpensamentos\x12\x1b\n" +
	"\tdata_hora\x18\x05 \x01(\tR\bdataHora\">\n" +
	"\fEmotionScore\x12\x18\n" +
	"\aemotion\x18\x01 \x01(\tR\aemotion\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"\xd6\x02\n" +
	"\x0fAnalyzeResponse\x12+\n" +
	"\x11emotion_principal\x18\x01 \x01(\tR\x10emotionPrincipal\x12-\n" +
	"\bemotions\x18\x02 \x03(\v2\x11.nlp.EmotionScoreR\bemotions\x128\n" +
	"\x06scores\x18\x03 \x03(\v2 .nlp.AnalyzeResponse.ScoresEntryR\x06scores\x12 \n" +
	"\vintensidade\x18\x04 \x01(\x02R\vintensidade\x12+\n" +
	"\x11analise_adicional\x18\x05 \x01(\tR\x10analiseAdicional\x12#\n" +
	"\rmodelo_versao\x18\x06 \x01(\tR\fmodeloVersao\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x012G\n" +
	"\x0fAnalysisService\x124\n" +
	"\aAnalyze\x12\x13.nlp.AnalyzeRequest\x1a\x14.nlp.AnalyzeResponseB/Z-github.com/edson/kanso-api/internal/nlp/protob\x06proto3"

var (
	file_analysis_proto_rawDescOnce sync.Once
	file_analysis_proto_rawDescData []byte
)

func file_analysis_proto_rawDescGZIP() []byte {
	file_analysis_proto_rawDescOnce.Do(func() {
		file_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)))
	})
	return file_analysis_proto_rawDescData
}

var file_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_analysis_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: nlp.AnalyzeRequest
	(*EmotionScore)(nil),    // 1: nlp.EmotionScore
	(*AnalyzeResponse)(nil), // 2: nlp.AnalyzeResponse
	nil,                     // 3: nlp.AnalyzeResponse.ScoresEntry
}
var file_analysis_proto_depIdxs = []int32{
	1, // 0: nlp.AnalyzeResponse.emotions:type_name -> nlp.EmotionScore
	3, // 1: nlp.AnalyzeResponse.scores:type_name -> nlp.AnalyzeResponse.ScoresEntry
	0, // 2: nlp.AnalysisService.Analyze:input_type -> nlp.AnalyzeRequest
	2, // 3: nlp.AnalysisService.Analyze:output_type -> nlp.AnalyzeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_analysis_proto_init() }
func file_analysis_proto_init() {
	if File_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analysis_proto_goTypes,
		DependencyIndexes: file_analysis_proto_depIdxs,
		MessageInfos:      file_analysis_proto_msgTypes,
	}.Build()
	File_analysis_proto = out.File
	file_analysis_proto_goTypes = nil
	file_analysis_proto_depIdxs = nil
}
